
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 5.15.180.1-1.cm2 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is AppleClang using "--version" did not match "(Apple (clang|LLVM) version)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is Clang using "--version" did not match "(clang version)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is ARMClang using "--version" did not match "armclang":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is OrangeC using "--version" did not match "occ \\(OrangeC\\) Version":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is HP using "-V" did not match "HP C":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is Intel using "--version" did not match "(ICC)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is IntelLLVM using "--version" did not match "(Intel[^
      ]+oneAPI)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is SunPro using "-V" did not match "Sun C":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is XL using "-qversion" did not match "XL C":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is MSVC using "-?" did not match "Microsoft":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is TI using "-h" did not match "Texas Instruments":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is TIClang using "--version" did not match "(TI (.*) Clang Compiler)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is IAR using "" did not match "IAR Assembler":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is ARMCC using "" did not match "(ARM Compiler)|(ARM Assembler)|(Arm Compiler)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is NASM using "-v" did not match "(NASM version)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is YASM using "--version" did not match "(yasm)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is ADSP using "-version" did not match "Analog Devices":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is QCC using "-V" did not match "gcc_nto":
  -
    kind: "message-v1"
    backtrace:
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/.local/lib/python3.11/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineASM_NASMCompiler.cmake:29 (include)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM_NASM compiler is Tasking using "--version" did not match "TASKING":
